kb = {
    'PERIOD': [
        '1st',
        '2nd',
        '3rd',
        '4th',
        'OT',
    ],
    'TEAM': [
        'ARZ',
        'Arizona',
        'ATL',
        'Atlanta',
        'BLT',
        'Baltimore',
        'BUF',
        'Buffalo',
        'CAR',
        'Carolina',
        'CHI',
        'Chicago',
        'CIN',
        'Cinncinatti',
        'CLV',
        'Cleveland',
        'DAL',
        'Dallas',
        'DEN',
        'Denver',
        'DET',
        'Detroit',
        'GB',
        'Green Bay',
        'HST',
        'Houston',
        'IND',
        'Indianapolis',
        'JAX',
        'Jacksonville',
        'KC',
        'Kansas City',
        'LA',
        'Los Angeles Rams',
        'LAC',
        'Los Angeles Chargers',
        'LV',
        'Las Vegas',
        'MIA',
        'Miami',
        'MIN',
        'Minnesota',
        'NE',
        'New England',
        'NO',
        'New Orleans',
        'NYG',
        'New York Giants',
        'NYJ',
        'New York Jets',
        'PHI',
        'Philadelphia',
        'PIT',
        'Pittsburgh',
        'SEA',
        'Seattle',
        'SF',
        'San Francisco',
        'TB',
        'Tampa Bay',
        'TEN',
        'Tennessee',
        'WAS',
        'Washington',
    ]
}
